### ISSUE TITLE
Error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by michaelBenin** [emostar/express-graceful-exit#10]
Seeing this error in our app. Hard to reproduce. We handle more traffic than an average site. Fix looks simple. 

```
TypeError: Cannot read property 'length' of undefined
    at Timeout._onTimeout (/media/ephemeral0/fc-2017-app/release-build-583/node_modules/express-graceful-exit/lib/graceful-exit.js:121:38)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by ivolucien** [comment]
@michaelBenin - thanks for the report, and it does look simple.  :+1:

**Comment by michaelBenin** [comment]
Thanks @ivolucien

**Comment by michaelBenin** [comment]
Thanks - no longer seeing this error.
